from college_course_recommender_system_utils import *

user_data, user_timestamp = get_user_data_and_timestamp()

user_college_course_preferences = get_user_college_course_preferences(user_data)

user_interest_questions_results_vector = get_user_interest_questions_results_vector(user_data)

baseline_college_course_recommendations = get_baseline_college_course_recommendations(user_interest_questions_results_vector, user_college_course_preferences)

actual_college_course_recommendations = get_college_course_recommendations(user_interest_questions_results_vector, user_college_course_preferences)

write_user_college_course_recommendations_to_csv(user_timestamp, actual_college_course_recommendations, baseline_college_course_recommendations)

write_user_college_course_recommendations_to_markdown(actual_college_course_recommendations, baseline_college_course_recommendations)
