from college_course_recommender_system_utils import *
from evaluation_utils import *

# Generate Recommendations
user_data_part_1, user_timestamp_part_1 = get_user_data_and_timestamp(SURVEY_PART_1_RESPONSES_DATASET_LOCATION)

user_college_course_preferences = get_user_college_course_preferences(user_data_part_1)

user_interest_questions_results_vector = get_user_interest_questions_results_vector(user_data_part_1)

baseline_college_course_recommendations = get_baseline_college_course_recommendations(user_interest_questions_results_vector, user_college_course_preferences)

actual_college_course_recommendations = get_college_course_recommendations(user_interest_questions_results_vector, user_college_course_preferences)

write_user_college_course_recommendations_to_markdown(actual_college_course_recommendations, baseline_college_course_recommendations)

# Evaluation
user_data_part_2, user_timestamp_part_2 = get_user_data_and_timestamp(SURVEY_PART_2_RESPONSES_DATASET_LOCATION)

write_user_evaluation_to_csv(user_data_part_2, user_timestamp_part_1, user_timestamp_part_2, actual_college_course_recommendations, baseline_college_course_recommendations)
